### ISSUE TITLE
Add a way to see site and user navbar buttons

### ISSUE THREAD

**Issue by rorepoid** [rorepoid/passport-authorization-server#20]
Actually This project has User Site and Settings buttons in navbar
But in mobile version User and Site buttons are not showing, and there are not ways to access, only typing the url 😨 

![image](https://user-images.githubusercontent.com/43040385/95252591-c8ee5d00-07e2-11eb-8332-249b960cc925.png)

![image](https://user-images.githubusercontent.com/43040385/95252702-f0ddc080-07e2-11eb-99c3-290b5a0466b8.png)

**Comment by Wavist** [comment]
I'd like to be assigned to this please

**Comment by rorepoid** [comment]
Sure @Wavist

**Comment by Wavist** [comment]
Where can i find the index file, the file i should work on.

**Comment by rorepoid** [comment]
Oh, the file with that component is in `resources\views\livewire\nav-bar.blade.php`

To up the project, there are basic steps in README

But if you have any question feel free to ask me :D

**Comment by Wavist** [comment]
Okay 
Sent from Yahoo Mail on Android 
 
  On Thu, 8 Oct 2020 at 16:37, Roberto Orellana Aliano<notifications@github.com> wrote:   


Oh, the file with that component is in resources\views\livewire\nav-bar.blade.php

To up the project, there are basic steps in README

But if you have any question feel free to ask me :D

**Comment by Wavist** [comment]
Hello, i haven't worked with laravel before just vanilla php so I'm having a hard time running the page. :(

**Comment by rorepoid** [comment]
Hi @Wavist , I'm sorry for this late answer. I need to improve the documentation to make it easier to understand how to run the project and explain how it will work. 

I added some additional information about the installation
Also if you tell me where you got stuck, I can try to help you :D

**Comment by Wavist** [comment]
when I'm trying to serve .. it says it cant find autoload.php. The file is missing

**Comment by rorepoid** [comment]
Maybe there was an error when you run `composer install`
Do you see any error message when running that?

**Comment by Wavist** [comment]
Lemme reinstall it

**Comment by Wavist** [comment]
Hello, http://localhost/laravel/passport-authorization-server/public/login. Can't signin.

**Comment by rorepoid** [comment]
username: `johndoe@example.com`
password: `secret`

**Comment by rorepoid** [comment]
When you use a laravel project, you should go to `.env` file located in the project root directory.
Then you see some enviroment variables, to set Database credentials you need to add values to the following variables

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=your_database_name
DB_USERNAME=your_username #example root
DB_PASSWORD=your_ultra_secret_password
```

**Comment by rorepoid** [comment]
Also if you run `php artisan serve` and it works well, you can see the project in `http://127.0.0.1:8000`, but this is optional if you are not using laragon, valet or any virtual host. In this case you only need to make sure your database server is running because apache or nginx will not be needed :D
![image](https://user-images.githubusercontent.com/43040385/95690604-9d061980-0bde-11eb-8323-bcb459854881.png)

**Comment by Wavist** [comment]
Who knew I could learn this much from just attempting an issue. thanks. I've migrated the db to my localdb (xampp) but I encounter this error ..{These credentials do not match our records}. I'll have to import the usertableseed.php file

**Comment by rorepoid** [comment]
hehe mm... If you run seeders, you should have data with users to sign in
because in `database\seeders\UsersTableSeeder.php` file there are some available users(including `John Doe`) that seeders will create. And the seeders are ready to be executed.

If you wanna re migrate data with seeders you can run the following commands:
```
    php artisan migrate:fresh
    php artisan db:seed
```

or the same thing but in short version:

```
    php artisan migrate:fresh --seed
```

**Comment by Wavist** [comment]
I'm done, buttons are now visible for smaller screens. Sending a PR now

**Comment by Wavist** [comment]
Hello... i did a git remote add upstream ad i can't find the app.css file. Did you delete it in your main repo

**Comment by rorepoid** [comment]
I'm using Tailwind CSS 😅

**Comment by Wavist** [comment]
Did you get my PR?

**Comment by rorepoid** [comment]
Not yet ⌛

**Comment by Wavist** [comment]
remote: Permission to rorepoid/passport-authorization-server.git denied to Wavist.
fatal: unable to access 'https://github.com/rorepoid/passport-authorization-server.git/': The requested URL returned error: 403 

been giving me headaches all through today

**Comment by rorepoid** [comment]
Is this your branch? https://github.com/Wavist/passport-authorization-server/tree/new_branch
You must create a new branch from master with all commits (I see only 3 😅)
![image](https://user-images.githubusercontent.com/43040385/96197635-48350c80-0f18-11eb-809f-de181bb6bcfc.png)

Then only push on your new branch and you should be able to see the option to do a Pull Request on GitHub

**Comment by Wavist** [comment]
I did all that, it said nothing to compare so no PR could be made. Confused...thats why I was asking maybe if I've alreday sent a PR.

**Comment by rorepoid** [comment]
To be sure
`git checkout master` _// from your forked repo_
`git pull origin master` _// at this point you should be able to see 344 commits_
`git checkout -b new-branch` _// or another name_
_--- put your changes ---_
`git commit -am "your commit message"`
`git push origin new-branch`

I think it said there is nothing to compare because history is very different
Try this again please :D

**Comment by Wavist** [comment]
Just succesfully sent the PR. Thanks. This was where i was getting my primary issue To definitely be able to login using https protocol, I had to first set my authentication credential to the git Remote URI: git remote set-url origin https://yourusername@github.com/user/repo.git. If there are any problems feel free to hit me up.
