### ISSUE TITLE
Change factory uses to Laravel 8 factories

### ISSUE THREAD

**Issue by rorepoid** [rorepoid/passport-authorization-server#28]
**Example:**

From -> **`factory(User::class)->create();`**

To -> **`User::factory()->create();`**

Also remind to check all **tests** are passing

**Comment by cdterry87** [comment]
I can try to work on this, if that's okay.

**Comment by rorepoid** [comment]
Sure @cdterry87

**Comment by rorepoid** [comment]
Thanks @cdterry87 🎉
