### ISSUE TITLE
Personal access tokens list disappear and reappear when go to their route or refresh and takes too many time

### ISSUE THREAD

**Issue by rorepoid** [rorepoid/passport-authorization-server#8]
## The problem
When going to root route and it's showed the personal access tokens there is moment when the component disappears but the component had been shown before and then all component is refreshed.

The flow is some like this:

1. Go to root page or refresh the page, the component is shown
![Screenshot from 2020-08-04 04-57-28](https://user-images.githubusercontent.com/43040385/89282000-8193f680-d610-11ea-8a3c-9db0dcab8ce6.png)

2. The component disappears
![Screenshot from 2020-08-04 04-57-45](https://user-images.githubusercontent.com/43040385/89282041-8e184f00-d610-11ea-8def-dfd3baff9e0f.png)

3. The component reapears
![Screenshot from 2020-08-04 04-57-28](https://user-images.githubusercontent.com/43040385/89282058-92dd0300-d610-11ea-8ef9-7e8526b1410c.png)

**Comment by frankielee617** [comment]
Hi, Please review this [](url)https://github.com/rorepoid/passport-authorization-server/pull/26#issue-497235621

**Comment by rorepoid** [comment]
Thank you @frankielee617 
I appreciate your contribution

**Comment by frankielee617** [comment]
You're welcomed.

**Comment by rorepoid** [comment]
I push one change more to close this issue #27
